import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Realm Web + Next.js SSR demo </h1>
      <p>how it works:</p>
      <p>
        log in using this page:{" "}
        <Link href="/login">
          <button>login</button>
        </Link>
      </p>
      <p>
        then click the button on that page to view data fetched from App
        Services GraphQL server
      </p>
    </div>
  );
};

export default Home;
